In [24]:
import pandas as pd

In [ ]:
^ library untuk membaca file csv

In [26]:
location = r'C:\Users\Jaldi\Desktop\test.csv'
dt = pd.read_csv(location)

^ memanggil file test.csv

In [34]:
print(dt)

           name  movementSpeed  physicalAttack  armor    hp  mana
0         Layla            270             118     15  2500   424
1       Cyclops            250             107     18  2461   500
2      Minotaur            265             123     25  2705     0
3         Saber            265             121     17  2475   443
4         Roger            235             120     22  2580   450
5          Nana            250             110     17  2325   499
6          Akai            260             115     24  2769   422
7         Alice            240             109     21  2397   493
8         Alpha            236             121     20  2646   453
9       Alucard            265             118     21  2593     0
10        Argus            260             124     21  2628     0
11       Aurora            245             105     17  2441   500
12      Balmond            265             114     23  2602     0
13         Bane            265             117     23  2625   433
14        Bruno            240             116     17  2402   439
15         Chou            265             121     23  2598     0
16        Clint            248             122     20  2500   450
17       Diggie            250             115     16  2351   490
18        Estes            240             115     13  2161   545
19       Eudora            250             112     19  2524   468
20        Fanny            270             126     17  2402     0
21       Franco            255             116     25  2575   440
22        Freya            265             109     22  2673   462
23    Gatotkaca            260             120     20  2709   440
24         Gord            240             105     13  2302   570
25        Grock            260             135     21  2819   430
26       Harley            240             114     19  2501   490
27     Hayabusa            265             114     17  2555   479
28       Helcur            255             121     17  2599   440
29        Hilda            260             123     24  2909     0
30        Hylos            260             105     17  3309   430
31      Irithel            250             110     17  2540   438
32      Johnson            255             112     27  2809     0
33       Kagura            240             113     19  2380   519
34       Karina            265             121     20  2505   431
35       Karrie            240             112     17  2498   440
36     Lancelot            260             124     16  2546   450
37    Lapu-lapu            260             119     21  2628     0
38       Lolita            265             115     27  2545     0
39         Miya            235             114     17  2404   445
40       Moskov            240             125     16  2530   420
41      Natalia            265             121     18  2465   486
42       Odette            240             105     18  2491   495
43       Pharsa            240             109     15  2421   490
44      Rafaela            245             112     15  2265   545
45         Ruby            265             114     23  2709   430
46   Sun Wukong            265             114     23  2630   400
47      Tigreal            265             112     25  2756   450
48       Vexana            245             112     17  2421   490
49  Yi Sun-Shin            240             110     18  2520   438
50     Yun Zhao            270             123     25  2561   405
51        Zhask            240             107     15  2401   490

^ isi dari keluaran file test.csv

Perintah soal

Misi Anda adalah menentukan, apa peran dari masing-masing hero yang membutuhkan bantuan dari program Anda, dengan aturan sebagai berikut secara berurutan (hero mendapatkan peran yang paling awal memenuhi syarat):

    Heroes yang memiliki movementSpeed >= 270, akan mendapat peran sebagai MARKSMAN (huruf kapital semua)
    Heroes dengan mana >= 500, akan mendapat peran sebagai MAGE (huruf kapital semua)
    Heroes dengan armor >= 25, akan mendapat peran sebagai TANK (huruf kapital semua)
    Heroes dengan physicalAttack >= 121, akan mendapat peran sebagai ASSASSIN (huruf kapital semua)
    Heroes dengan hp >= 2580, akan mendapat peran sebagai FIGHTER (huruf kapital semua)
    Heroes lainnya akan mendapat peran sebagai SUPPORT (huruf kapital semua)

Jawab

In [28]:
Role = []
for i in range(len(dt)):
    if dt["movementSpeed"][i] >= 270:
        Role.append("MARKSMAN")
    elif dt["mana"][i] >= 500:
        Role.append("MAGE")
    elif dt["armor"][i] >= 25:
        Role.append("TANK")
    elif dt["physicalAttack"][i] >= 121:
        Role.append("ASSASSIN")
    elif dt["hp"][i] >= 2580:
        Role.append("FIGHTER")
    else:
        Role.append("SUPPORT")

^ syntax klasifikasi peran heroes

In [29]:
dp = pd.DataFrame({"name" : dt["name"],"role" : Role})

^ membuat data baru

In [35]:
dp.to_csv("prediction.csv", index = False)

^ mengkonversi data baru menjadi keluaran file berbentuk ".csv"

In [33]:
dp

           name      role
0         Layla  MARKSMAN
1       Cyclops      MAGE
2      Minotaur      TANK
3         Saber  ASSASSIN
4         Roger   FIGHTER
5          Nana   SUPPORT
6          Akai   FIGHTER
7         Alice   SUPPORT
8         Alpha  ASSASSIN
9       Alucard   FIGHTER
10        Argus  ASSASSIN
11       Aurora      MAGE
12      Balmond   FIGHTER
13         Bane   FIGHTER
14        Bruno   SUPPORT
15         Chou  ASSASSIN
16        Clint  ASSASSIN
17       Diggie   SUPPORT
18        Estes      MAGE
19       Eudora   SUPPORT
20        Fanny  MARKSMAN
21       Franco      TANK
22        Freya   FIGHTER
23    Gatotkaca   FIGHTER
24         Gord      MAGE
25        Grock  ASSASSIN
26       Harley   SUPPORT
27     Hayabusa   SUPPORT
28       Helcur  ASSASSIN
29        Hilda  ASSASSIN
30        Hylos   FIGHTER
31      Irithel   SUPPORT
32      Johnson      TANK
33       Kagura      MAGE
34       Karina  ASSASSIN
35       Karrie   SUPPORT
36     Lancelot  ASSASSIN
37    Lapu-lapu   FIGHTER
38       Lolita      TANK
39         Miya   SUPPORT
40       Moskov  ASSASSIN
41      Natalia  ASSASSIN
42       Odette   SUPPORT
43       Pharsa   SUPPORT
44      Rafaela      MAGE
45         Ruby   FIGHTER
46   Sun Wukong   FIGHTER
47      Tigreal      TANK
48       Vexana   SUPPORT
49  Yi Sun-Shin   SUPPORT
50     Yun Zhao  MARKSMAN
51        Zhask   SUPPORT

^ output hasil akhir